build-job:
  tags:
    -  build 
  script:
    - sudo -i
    - chmod -R a+rxw /home/gitlab-runner/builds
    - cd ./TheLake/
    - ./build-tag-push-docker.sh
    - cd ..
    - cd ./ThePier/
    - ./build-tag-push-docker.sh
    - cd ..
    - cd ./docker-setup/full
    - docker-compose down
    - docker-compose rm -f
    - docker-compose pull
    - docker-compose up -d
    - sleep 2m
    - docker-compose ps
    - docker-compose logs master
    - docker-compose logs namenode 
    - docker-compose logs master   
    - docker-compose logs mongodb  
    - docker-compose logs postgres  
    - docker-compose logs worker-2  
    - docker-compose logs worker-1  
    - docker-compose logs datanode1 
    - docker-compose logs datanode3 
    - docker-compose logs datanode2 
    - docker-compose logs backend         
    - docker-compose logs resourcemanager 
    - docker-compose logs historyserver   
    - docker-compose logs nodemanager1    
    - docker-compose logs pier 
    - docker-compose down

#test-job1:
#  tags:
#    - build
#  stage: test
#  script:
#    - echo "This job tests something"
#
#test-job2:
#  tags:
#    - Docker-Build
#  stage: test
#  script:
#    - echo "This job tests something, but takes more time than test-job1."
#    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#    - echo "which simulates a test that runs 20 seconds longer than test-job1"
#    - sleep 20