sparkMaster: "spark://localhost:7077"

jwt:
  secretKey: "sup3r_s3cr3t_k3y"
  tokenLocation: ["cookies"]
  accessCsrfHeaderName: "X-CSRF-TOKEN-ACCESS"
  cookieCsrfProtect: false
  accessTokenExpires: 90000000000
  refreshTokenExpires: 90000000000

serverMongodb:
  host: "localhost"
  port: 27017
  database: "datalake"
  user: "mapro2020"
  password: "mapro2020"

storages:
  mongodb: 
    host: "localhost"
    port: 27017
    database: "datalake_storage"
    user: "mapro2020"
    password: "mapro2020"

  postgresql:
    host: "localhost"
    port: 5432
    database: "datalake_storage"
    user: "mapro2020"
    password: "mapro2020"

  hdfs:
    namenode: "namenode"
    port: 9000
    ingestionDirectory: "datalake_ingestion"
    storageDirectory: "datalake_storage"

  fuseki:
    user: admin
    password: pw123
