version: "3"

services:
  master:
    image: master
    container_name: master
    ports:
      - 8080:8080
      - 7077:7077
      - 8998:8998
    networks:
      - spark

  worker-1:
    image: worker
    container_name: worker-1
    depends_on:
      - master
    ports:
      - 8081:8081
    networks:
      - spark

  worker-2:
    image: worker
    container_name: worker-2
    depends_on:
      - master
    ports:
      - 8082:8081
    networks:
      - spark

networks:
  spark:
    external: false
